name: Validation
description: format, lint, test code
runs:
  using: "composite"
  steps:
    - name: 📦 Install uv
      uses: astral-sh/setup-uv@v6

    - name: 🐍 Set up Python ${{ env.PY_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PY_VERSION }}

    - name: 🦾 Install dependencies
      run: uv sync --locked --all-extras --dev
      shell: bash

    - name: 💅 🧪 Validate!
      run: uv run poe flct
      shell: bash
